prefix="[dim]{timestamp}[/dim] | {tag} "

[[commands]]
tag = "one"
command = "while true; do sleep 1; echo hello; done"
prefix_style = "yellow"

[[commands]]
tag = "two"
command = "while true; do sleep 1.5; echo hi; done"
prefix_style = "cyan"

[[commands]]
tag = "ptw"
command = "ptw"
prefix_style = "bold green"
